# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcstree < Formula
  desc ""
  homepage ""
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/owlinux1000/gcstree/releases/download/v0.0.5/gcstree_Darwin_x86_64.tar.gz"
      sha256 "20291c4dc69d5fa7d34a34dd5023ef0b53e3c429a0e6934ef3cca786f83d1044"

      def install
        bin.install "gcstree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/owlinux1000/gcstree/releases/download/v0.0.5/gcstree_Darwin_arm64.tar.gz"
      sha256 "707c321ba193dc4ab59c312bf1655102dcaa27147a8ef03f097f42043315201f"

      def install
        bin.install "gcstree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/owlinux1000/gcstree/releases/download/v0.0.5/gcstree_Linux_x86_64.tar.gz"
      sha256 "c7627166aca39bdb61acec23a05961cc970c27ccda7910f7c3c8b685d7ecf51d"

      def install
        bin.install "gcstree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/owlinux1000/gcstree/releases/download/v0.0.5/gcstree_Linux_arm64.tar.gz"
      sha256 "9224c18994acf30aad4498f3a850af4d4a092ee678423ece8a2ce3ce5e3bd6ee"

      def install
        bin.install "gcstree"
      end
    end
  end
end
