# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcstree < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/owlinux1000/gcstree/releases/download/v0.0.3/gcstree_Darwin_x86_64.tar.gz"
      sha256 "b363913c81caf6b9bf3ac788b3a861b8488df0f19b4769940bb836d748445863"

      def install
        bin.install "gcstree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/owlinux1000/gcstree/releases/download/v0.0.3/gcstree_Darwin_arm64.tar.gz"
      sha256 "ab34f23d875faf41dbb60ff6d083b3960372590a57223a4046ba16ad46ea9e2a"

      def install
        bin.install "gcstree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/owlinux1000/gcstree/releases/download/v0.0.3/gcstree_Linux_x86_64.tar.gz"
      sha256 "36f5f224747613431155728417a6cc62ed07acdbaca968e18f9787deaa709180"

      def install
        bin.install "gcstree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/owlinux1000/gcstree/releases/download/v0.0.3/gcstree_Linux_arm64.tar.gz"
      sha256 "4f2e760618b94efd8539d0165cf7ac328ed44c33edbe2ae27bced0eb9851f844"

      def install
        bin.install "gcstree"
      end
    end
  end
end
