# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcstree < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/owlinux1000/gcstree/releases/download/v0.0.3/gcstree_Darwin_arm64.tar.gz"
      sha256 "441d9f38f824263460b6ffa62d5a972c39a8478d66c3dfb91a655e3aff95938c"

      def install
        bin.install "gcstree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/owlinux1000/gcstree/releases/download/v0.0.3/gcstree_Darwin_x86_64.tar.gz"
      sha256 "df8808b2b5b7c12674b430bb12c8016462ea794ec8d45142c254305e72bea00f"

      def install
        bin.install "gcstree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/owlinux1000/gcstree/releases/download/v0.0.3/gcstree_Linux_x86_64.tar.gz"
      sha256 "dd3d396c399195cf0ad00f64d347cad388e977323c1cfd81b99de62b7a2db77f"

      def install
        bin.install "gcstree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/owlinux1000/gcstree/releases/download/v0.0.3/gcstree_Linux_arm64.tar.gz"
      sha256 "b84dc0d512321ac384e5190d8f407edbddcf08cab980d22ce4a6e9a4ad5266bd"

      def install
        bin.install "gcstree"
      end
    end
  end
end
